"""
lithophane_cmy.py
=================

Convert an uploaded RGB image into everything needed to 3D-print a CMY
lithophane:

* Cyan / Magenta / Yellow **thickness channels** for a CMY lithophane
* A flat **base-plate STL** (default 0.6 mm thick)
* Three **CMY color-layer STLs** -- one per ink -- with a flat bottom and a
  heightmap top, each capped at 0.5 mm of thickness.
* A **lithotop STL** whose per-pixel height is driven by the luminance of
  the original image (shadows and highlights).

Print layout (Z grows upward, all dimensions in mm):

    z=2.0+    lithotop top  (varies with luminance)
    z=1.0+    lithotop bottom = base + max CMY stack height = 0.6 + 1.5
              â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ Yellow layer  top = 1.0 + Y*0.5
              â”‚ bottom = 1.0 (flat)
              â”œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ Magenta layer top = 0.5 + M*0.5
              â”‚ bottom = 0.5 (flat)
              â”œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ Cyan layer    top = 0.0 + C*0.5
              â”‚ bottom = 0.0 (flat)
    z=0.0      Base plate (flat, 0.6 mm thick)

CMY channel mapping (subtractive colour model):

    C  = 1 - R_norm        # cyan   absorbs red   light
    M  = 1 - G_norm        # magenta absorbs green light
    Y  = 1 - B_norm        # yellow  absorbs blue  light

    1.0 -> the pixel should be printed at MAX thickness (it absorbs /
           blocks the most light of that colour)
    0.0 -> the pixel should be printed at MIN thickness (lets the colour
           through)

Lithotop luminance (BT.601):

    L  = 0.299 R + 0.587 G + 0.114 B
    z_top = base + 3*max_cmy + z_min + (1 - L) * (z_max - z_min)

Pipeline
--------
1.  Load RGB image (any mode -> converted to RGB).
2.  Resize to a target physical size (width_mm, height_mm) at a chosen
    resolution (px_per_mm).  Aspect ratio is preserved by default.
3.  Normalise to float32 in [0, 1].
4.  Split into Cyan, Magenta, Yellow thickness channels.
5.  Compute BT.601 luminance for the lithotop layer.
6.  Build the base plate, three CMY color layers and the lithotop meshes.

Alignment guarantee
-------------------
All five STL meshes share **bit-exact X and Y coordinates**:

* every mesh is generated by ``_make_column_heightmap_stl`` (or
  ``make_base_plate_stl``) using the same ``width_mm``, ``height_mm`` and
  pixel grid, so each pixel ``(i, j)`` sits at exactly the same ``(x, y)``
  position in every STL;
* all X coordinates lie in ``[0, width_mm]``, all Y coordinates lie in
  ``[0, height_mm]``, and every mesh's bounding box is identical to within
  floating-point precision.

Call :func:`verify_xy_alignment` (or ``result.verify_alignment()``) to
assert this in your own code; the CLI runs the same check by default when
STLs are emitted.

Slicer-friendly file naming
----------------------------
By default :func:`save_stls` writes five numbered STLs in the order a
multi-material slicer (Bambu Studio, PrusaSlicer, OrcaSlicer, ...) should
load them:

    1_Base_White.stl     (the structural base plate)
    2_Cyan.stl           (cyan color layer)
    3_Magenta.stl        (magenta color layer)
    4_Yellow.stl         (yellow color layer)
    5_Top_White.stl      (lithotop / luminance-driven top white layer)

The numeric prefixes force the load order in most slicers; the colour
names make the files self-documenting.

Typical use
-----------
    # CLI
    python lithophane_cmy.py photo.jpg --width 100 --height 100 --px-per-mm 10
    python lithophane_cmy.py --demo

    # Programmatic
    from lithophane_cmy import process_image
    result = process_image("photo.jpg")
    C, M, Y = result.channels
    result.base_stl              # base plate
    result.cyan_layer_stl        # cyan color layer
    result.magenta_layer_stl     # magenta color layer
    result.yellow_layer_stl      # yellow color layer
    result.lithotop_stl          # white luminance layer
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Optional, Tuple, Union

import numpy as np
from PIL import Image

# ---------------------------------------------------------------------------
# Optional numpy-stl import (STL output is skipped cleanly if not installed)
# ---------------------------------------------------------------------------
try:
    from stl import mesh as _stl_mesh  # type: ignore
    _HAS_NUMPY_STL = True
except ImportError:                    # pragma: no cover
    _stl_mesh = None                   # type: ignore
    _HAS_NUMPY_STL = False

try:
    import trimesh as _trimesh         # type: ignore
    _HAS_TRIMESH = True
except ImportError:                    # pragma: no cover
    _trimesh = None                    # type: ignore
    _HAS_TRIMESH = False


# ---------------------------------------------------------------------------
# Configuration helpers
# ---------------------------------------------------------------------------

_RESAMPLE = Image.Resampling.LANCZOS

# Base plate (the structural floor of the print).  Hard-coded for standard
# CMYK filament profiles; not exposed in the Streamlit UI.
DEFAULT_BASE_THICKNESS_MM: float = 0.6

# Each CMY color layer can be at most this thick (capped per the spec).
# Hard-coded for standard CMYK filament profiles; not exposed in the UI.
DEFAULT_MAX_CMY_THICKNESS_MM: float = 0.4

# Lithotop (top white layer) thickness range, added ON TOP of the
# base plate + stacked CMY layers.  Exposed in the UI as
# "Min Thickness" / "Max Thickness" with a 0.1 mm step.
DEFAULT_LITHOTOP_MIN_MM: float = 0.8
DEFAULT_LITHOTOP_MAX_MM: float = 5.0

# Default border width (mm) added around the perimeter of every layer to
# prevent light bleed.  Set to 0 to disable.
DEFAULT_BORDER_WIDTH_MM: float = 2.0

# Structural outer frame (a separate hollow rectangular ring STL).
# These are exposed in the UI as "Frame Width" and "Frame Depth".
DEFAULT_FRAME_WIDTH_MM: float = 2.0   # X/Y thickness of the frame ring
DEFAULT_FRAME_DEPTH_MM: float = 1.0   # Z thickness of the frame ring
DEFAULT_FRAME_ENABLED: bool = True

# BT.601 luminance weights (R, G, B).
_LUMA_WEIGHTS = np.array([0.299, 0.587, 0.114], dtype=np.float32)


@dataclass(frozen=True)
class PhysicalSize:
    """A physical size expressed in millimetres."""

    width_mm: float
    height_mm: float

    def as_pixels(self, px_per_mm: float) -> Tuple[int, int]:
        """Convert the physical size to pixel dimensions at *px_per_mm*."""
        if px_per_mm <= 0:
            raise ValueError(f"px_per_mm must be > 0, got {px_per_mm}")
        w = max(1, int(round(self.width_mm * px_per_mm)))
        h = max(1, int(round(self.height_mm * px_per_mm)))
        return w, h


# ---------------------------------------------------------------------------
# Core image processing
# ---------------------------------------------------------------------------

def load_rgb_image(source: Union[str, Path, Image.Image]) -> Image.Image:
    """Load *source* and return it as an 8-bit RGB :class:`PIL.Image.Image`."""
    if isinstance(source, Image.Image):
        img = source
    else:
        path = Path(source)
        if not path.is_file():
            raise FileNotFoundError(f"Image not found: {path}")
        img = Image.open(path)
        img.load()
    if img.mode != "RGB":
        img = img.convert("RGB")
    return img


def compute_target_pixels(
    src_size: Tuple[int, int],
    width_mm: float,
    height_mm: float,
    px_per_mm: float,
    preserve_aspect: bool = True,
) -> Tuple[int, int]:
    """Return the (width_px, height_px) the image should be resized to."""
    target_w_px, target_h_px = PhysicalSize(width_mm, height_mm).as_pixels(px_per_mm)
    if preserve_aspect:
        src_w, src_h = src_size
        if src_w == 0 or src_h == 0:
            return target_w_px, target_h_px
        scale = min(target_w_px / src_w, target_h_px / src_h)
        target_w_px = max(1, int(round(src_w * scale)))
        target_h_px = max(1, int(round(src_h * scale)))
    return target_w_px, target_h_px


def resize_to_physical(
    img: Image.Image,
    width_mm: float,
    height_mm: float,
    px_per_mm: float,
    preserve_aspect: bool = True,
) -> Image.Image:
    """Resize *img* to the requested physical dimensions at *px_per_mm*."""
    target_w_px, target_h_px = compute_target_pixels(
        img.size, width_mm, height_mm, px_per_mm, preserve_aspect
    )
    if img.size == (target_w_px, target_h_px):
        return img
    return img.resize((target_w_px, target_h_px), resample=_RESAMPLE)


def rgb_to_cmy_thickness(
    img_rgb_float: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Split an H x W x 3 float image in [0, 1] into CMY thickness channels.

    Subtractive mapping:
        C = 1 - R          (cyan   blocks red   light)
        M = 1 - G          (magenta blocks green light)
        Y = 1 - B          (yellow  absorbs blue  light)
    """
    if img_rgb_float.ndim != 3 or img_rgb_float.shape[2] != 3:
        raise ValueError(
            f"Expected an H x W x 3 array, got shape {img_rgb_float.shape}"
        )
    arr = img_rgb_float.astype(np.float32, copy=False)
    np.clip(arr, 0.0, 1.0, out=arr)
    C = 1.0 - arr[..., 0]
    M = 1.0 - arr[..., 1]
    Y = 1.0 - arr[..., 2]
    return C.astype(np.float32), M.astype(np.float32), Y.astype(np.float32)


def _pad_with_ones(grid: np.ndarray, border_px: int) -> np.ndarray:
    """Pad a grid with border_px rows/cols of 1.0 on every side.

    Accepts both ``(H, W)`` 2-D arrays (single CMY channel / luminance)
    and ``(H, W, C)`` 3-D arrays (RGB image).  Only the first two axes
    are padded; channel axis (if present) is left untouched.
    """
    if border_px <= 0:
        return grid
    pad_width = [(border_px, border_px), (border_px, border_px)]
    if grid.ndim == 3:
        pad_width.append((0, 0))
    return np.pad(
        grid.astype(np.float32, copy=False),
        pad_width,
        mode="constant", constant_values=1.0,
    )


def rgb_to_luminance(img_rgb_float: np.ndarray) -> np.ndarray:
    """Compute BT.601 luminance for an H x W x 3 float image in [0, 1]."""
    if img_rgb_float.ndim != 3 or img_rgb_float.shape[2] != 3:
        raise ValueError(
            f"Expected an H x W x 3 array, got shape {img_rgb_float.shape}"
        )
    arr = img_rgb_float.astype(np.float32, copy=False)
    np.clip(arr, 0.0, 1.0, out=arr)
    luma = arr @ _LUMA_WEIGHTS
    return luma.astype(np.float32)


# ---------------------------------------------------------------------------
# STL geometry (numpy-stl)
# ---------------------------------------------------------------------------

def _require_stl() -> None:
    """Raise a friendly error if numpy-stl is not installed."""
    if not _HAS_NUMPY_STL:
        raise RuntimeError(
            "numpy-stl is required for STL output but is not installed.\n"
            "Install it with:  python -m pip install numpy-stl"
        )


def _empty_stl_mesh(n_triangles: int):
    """Return a numpy-stl ``Mesh`` pre-allocated for *n_triangles* triangles."""
    _require_stl()
    return _stl_mesh.Mesh(np.zeros(n_triangles, dtype=_stl_mesh.Mesh.dtype))


def make_base_plate_stl(
    width_mm: float,
    height_mm: float,
    base_thickness_mm: float = DEFAULT_BASE_THICKNESS_MM,
):
    """Build the flat rectangular base plate as a numpy-stl ``Mesh``.

    Occupies ``x âˆˆ [0, width_mm]``, ``y âˆˆ [0, height_mm]``,
    ``z âˆˆ [0, base_thickness_mm]``.  12 triangles (2 per face Ã— 6 faces).
    """
    _require_stl()
    if width_mm <= 0 or height_mm <= 0 or base_thickness_mm <= 0:
        raise ValueError("width_mm, height_mm and base_thickness_mm must be > 0")

    w, h, t = float(width_mm), float(height_mm), float(base_thickness_mm)
    vertices = np.array(
        [
            [0.0, 0.0, 0.0], [w,   0.0, 0.0], [w,   h,   0.0], [0.0, h,   0.0],
            [0.0, 0.0, t],   [w,   0.0, t],   [w,   h,   t],   [0.0, h,   t],
        ],
        dtype=np.float64,
    )
    face_indices = np.array(
        [
            [0, 2, 1], [0, 3, 2],                     # bottom (-Z)
            [4, 5, 6], [4, 6, 7],                     # top    (+Z)
            [0, 1, 5], [0, 5, 4],                     # y = 0  (-Y)
            [1, 2, 6], [1, 6, 5],                     # x = w  (+X)
            [2, 3, 7], [2, 7, 6],                     # y = h  (+Y)
            [3, 0, 4], [3, 4, 7],                     # x = 0  (-X)
        ],
        dtype=np.int32,
    )
    triangles = vertices[face_indices]
    plate = _empty_stl_mesh(triangles.shape[0])
    plate.vectors[:] = triangles.astype(np.float32)
    return plate


# ---- shared column-heightmap mesh helper -----------------------------------

# 12 triangles per pixel, CCW when viewed from outside the column.
_COLUMN_TRI_IDX = np.array(
    [
        [0, 2, 1], [0, 3, 2],                     # bottom (normal -Z)
        [4, 5, 6], [4, 6, 7],                     # top    (normal +Z)
        [0, 1, 5], [0, 5, 4],                     # y = y0 (normal -Y)
        [1, 2, 6], [1, 6, 5],                     # x = x1 (normal +X)
        [2, 3, 7], [2, 7, 6],                     # y = y1 (normal +Y)
        [3, 0, 4], [3, 4, 7],                     # x = x0 (normal -X)
    ],
    dtype=np.int32,
)


def _make_column_heightmap_stl(
    width_mm: float,
    height_mm: float,
    bottom_z: np.ndarray,    # (H, W) bottom-Z of each pixel column
    top_z: np.ndarray,       # (H, W) top-Z of each pixel column
):
    """Build an STL mesh of independent rectangular columns.

    For each pixel ``(i, j)`` a rectangular box is emitted whose bottom sits
    at ``bottom_z[i, j]`` and whose top sits at ``top_z[i, j]``.  The X/Y
    position of pixel ``(i, j)`` is centred on the pixel cell.  12 triangles
    per pixel are emitted (2 bottom, 2 top, 8 side walls).
    """
    _require_stl()
    if bottom_z.shape != top_z.shape or bottom_z.ndim != 2:
        raise ValueError(
            f"bottom_z and top_z must be 2-D arrays of identical shape, "
            f"got {bottom_z.shape} vs {top_z.shape}"
        )
    if width_mm <= 0 or height_mm <= 0:
        raise ValueError("width_mm and height_mm must be > 0")

    H, W = bottom_z.shape
    px_w = float(width_mm) / W
    px_h = float(height_mm) / H

    # Y is flipped so the image is right-side-up when looking at the print
    # from above with +Z up and +Y going away from the viewer.
    cx = (np.arange(W, dtype=np.float64) + 0.5) * px_w
    cy = (H - np.arange(H, dtype=np.float64) - 0.5) * px_h
    cx_grid, cy_grid = np.meshgrid(cx, cy)

    x0 = cx_grid - 0.5 * px_w
    x1 = cx_grid + 0.5 * px_w
    y0 = cy_grid - 0.5 * px_h
    y1 = cy_grid + 0.5 * px_h

    bottom_z = np.asarray(bottom_z, dtype=np.float64)
    top_z = np.asarray(top_z, dtype=np.float64)

    # 8 corner vertices per pixel:  bottom 0..3, top 4..7 (CCW outside).
    verts = np.stack(
        [
            np.stack([x0, y0, bottom_z], axis=-1),  # 0
            np.stack([x1, y0, bottom_z], axis=-1),  # 1
            np.stack([x1, y1, bottom_z], axis=-1),  # 2
            np.stack([x0, y1, bottom_z], axis=-1),  # 3
            np.stack([x0, y0, top_z], axis=-1),     # 4
            np.stack([x1, y0, top_z], axis=-1),     # 5
            np.stack([x1, y1, top_z], axis=-1),     # 6
            np.stack([x0, y1, top_z], axis=-1),     # 7
        ],
        axis=-2,
    )                                                # (H, W, 8, 3)

    triangles = verts[..., _COLUMN_TRI_IDX, :]      # (H, W, 12, 3, 3)
    triangles = triangles.reshape(-1, 3, 3).astype(np.float32)

    mesh_obj = _empty_stl_mesh(triangles.shape[0])
    mesh_obj.vectors[:] = triangles
    return mesh_obj


def make_cmy_layer_stl(
    width_mm: float,
    height_mm: float,
    layer_bottom_z: float,
    channel_intensity: np.ndarray,        # (H, W) float32 in [0, 1]
    max_thickness_mm: float = DEFAULT_MAX_CMY_THICKNESS_MM,
):
    """Build a single CMY color-layer STL with a flat bottom and a
    heightmap top.

    For every pixel ``(i, j)`` the local column extends from the FLAT bottom
    z = ``layer_bottom_z`` to a top z that is a heightmap driven by the
    pixel's intensity:

        z_top[i, j] = layer_bottom_z + channel_intensity[i, j] * max_thickness_mm

    *channel_intensity* is clipped into [0, 1].  The total per-pixel thickness
    is capped at ``max_thickness_mm`` (default **0.5 mm**).
    """
    _require_stl()
    if channel_intensity.ndim != 2:
        raise ValueError(
            f"channel_intensity must be 2-D (H, W), got shape "
            f"{channel_intensity.shape}"
        )
    if max_thickness_mm <= 0:
        raise ValueError("max_thickness_mm must be > 0")

    intensity = np.clip(
        channel_intensity.astype(np.float32, copy=False), 0.0, 1.0
    )
    bottom = np.full_like(intensity, float(layer_bottom_z), dtype=np.float64)
    top = float(layer_bottom_z) + intensity.astype(np.float64) * float(
        max_thickness_mm
    )
    return _make_column_heightmap_stl(width_mm, height_mm, bottom, top)


def make_cmy_layers_stls(
    width_mm: float,
    height_mm: float,
    cyan: np.ndarray,                    # (H, W) float32 in [0, 1]
    magenta: np.ndarray,
    yellow: np.ndarray,
    max_thickness_mm: float = DEFAULT_MAX_CMY_THICKNESS_MM,
    base_bottom_z: float = 0.0,
):
    """Build the three stacked CMY color-layer STLs in a single call.

    The layers are stacked (Cyan at the bottom, then Magenta, then Yellow)
    so that the bottom of each layer is flat at the maximum thickness of the
    layer below it:

        Cyan    bottom z = base_bottom_z
                top    z = base_bottom_z + C * max_thickness_mm
        Magenta bottom z = base_bottom_z + max_thickness_mm
                top    z = base_bottom_z + max_thickness_mm + M * max_thickness_mm
        Yellow  bottom z = base_bottom_z + 2 * max_thickness_mm
                top    z = base_bottom_z + 2 * max_thickness_mm + Y * max_thickness_mm

    Returns a dict ``{"cyan": Mesh, "magenta": Mesh, "yellow": Mesh}``.
    """
    _require_stl()
    if cyan.shape != magenta.shape or magenta.shape != yellow.shape:
        raise ValueError(
            "cyan, magenta and yellow must have the same shape; got "
            f"{cyan.shape}, {magenta.shape}, {yellow.shape}"
        )
    if cyan.ndim != 2:
        raise ValueError("CMY channels must be 2-D (H, W)")

    z_cyan_bottom = float(base_bottom_z)
    z_magenta_bottom = z_cyan_bottom + float(max_thickness_mm)
    z_yellow_bottom = z_magenta_bottom + float(max_thickness_mm)

    return {
        "cyan": make_cmy_layer_stl(
            width_mm, height_mm, z_cyan_bottom, cyan, max_thickness_mm
        ),
        "magenta": make_cmy_layer_stl(
            width_mm, height_mm, z_magenta_bottom, magenta, max_thickness_mm
        ),
        "yellow": make_cmy_layer_stl(
            width_mm, height_mm, z_yellow_bottom, yellow, max_thickness_mm
        ),
    }


def make_lithotop_stl(
    width_mm: float,
    height_mm: float,
    base_thickness_mm: float,
    rgb_normalized: np.ndarray,
    lithotop_min_mm: float = DEFAULT_LITHOTOP_MIN_MM,
    lithotop_max_mm: float = DEFAULT_LITHOTOP_MAX_MM,
    lithotop_bottom_z: Optional[float] = None,
):
    """Build the top white (lithotop) layer as a numpy-stl ``Mesh``.

    Each pixel becomes an independent rectangular column whose height is
    driven by the BT.601 luminance of that pixel (darker = taller).

    By default the bottom of the lithotop sits on top of the base plate,
    i.e. at ``z = base_thickness_mm``.  When stacking CMY color layers
    underneath, pass ``lithotop_bottom_z`` explicitly.
    """
    _require_stl()
    if rgb_normalized.ndim != 3 or rgb_normalized.shape[2] != 3:
        raise ValueError(
            f"rgb_normalized must be H x W x 3, got {rgb_normalized.shape}"
        )
    if lithotop_max_mm < lithotop_min_mm:
        raise ValueError("lithotop_max_mm must be >= lithotop_min_mm")

    luma = rgb_to_luminance(rgb_normalized)                # (H, W) in [0, 1]
    z_extra = float(lithotop_min_mm) + (1.0 - luma) * float(
        lithotop_max_mm - lithotop_min_mm
    )
    bottom_z_default = float(base_thickness_mm)
    z_bottom = (
        float(lithotop_bottom_z)
        if lithotop_bottom_z is not None
        else bottom_z_default
    )
    bottom = np.full_like(luma, z_bottom, dtype=np.float64)
    top = bottom + z_extra.astype(np.float64)
    return _make_column_heightmap_stl(width_mm, height_mm, bottom, top)


def make_frame_stl(
    width_mm: float,
    height_mm: float,
    frame_width_mm: float = DEFAULT_FRAME_WIDTH_MM,
    frame_depth_mm: float = DEFAULT_FRAME_DEPTH_MM,
    bottom_z: float = 0.0,
):
    """Build a hollow rectangular **frame ring** STL.

    The frame is a rectangular ring that wraps the outer perimeter of the
    print.  The outer rectangle is ``width_mm x height_mm``; the inner
    rectangle is ``(width_mm - 2*frame_width_mm) x (height_mm - 2*frame_width_mm)``.
    The ring is solid in Z from ``bottom_z`` to ``bottom_z + frame_depth_mm``.

    Returns ``None`` if ``frame_width_mm <= 0`` or ``frame_depth_mm <= 0``
    or if the inner rectangle would be degenerate.  This is by design so
    that the UI can simply pass ``0`` to disable the frame.

    The frame shares the same X/Y origin as the lithotop and base plate
    (it is anchored at x = 0, y = 0), so it stacks correctly in slicers.
    """
    _require_stl()
    if frame_width_mm <= 0 or frame_depth_mm <= 0:
        return None
    if width_mm <= 0 or height_mm <= 0:
        raise ValueError("width_mm and height_mm must be > 0")

    outer_w = float(width_mm)
    outer_h = float(height_mm)
    inner_w = outer_w - 2.0 * float(frame_width_mm)
    inner_h = outer_h - 2.0 * float(frame_width_mm)
    if inner_w <= 0 or inner_h <= 0:
        return None

    z0 = float(bottom_z)
    z1 = z0 + float(frame_depth_mm)
    x0, x1 = 0.0, outer_w
    y0, y1 = 0.0, outer_h
    ix0, ix1 = float(frame_width_mm), float(frame_width_mm) + inner_w
    iy0, iy1 = float(frame_width_mm), float(frame_width_mm) + inner_h

    # ---- bottom rectangle (outer) ------------------------------------------
    bot_outer = [
        (x0, y0), (x1, y0), (x1, y1), (x0, y1)
    ]
    # ---- bottom rectangle (inner) ------------------------------------------
    bot_inner = [
        (ix0, iy0), (ix1, iy0), (ix1, iy1), (ix0, iy1)
    ]

    triangles = []  # list of (v0, v1, v2)

    def tri(a, b, c):
        triangles.append((a, b, c))

    # Bottom face: outer CCW (-Z) plus inner CW (-Z) so the ring is solid.
    tri((x0, y0, z0), (x1, y0, z0), (x1, y1, z0))
    tri((x0, y0, z0), (x1, y1, z0), (x0, y1, z0))
    tri((ix0, iy0, z0), (ix1, iy1, z0), (ix1, iy0, z0))
    tri((ix0, iy0, z0), (ix0, iy1, z0), (ix1, iy1, z0))

    # Top face: outer CCW (+Z) plus inner CW (+Z).
    tri((x0, y0, z1), (x0, y1, z1), (x1, y1, z1))
    tri((x0, y0, z1), (x1, y1, z1), (x1, y0, z1))
    tri((ix0, iy0, z1), (ix1, iy0, z1), (ix1, iy1, z1))
    tri((ix0, iy0, z1), (ix1, iy1, z1), (ix0, iy1, z1))

    # Outer side walls (4 faces, each split into 2 tris).
    # -Y wall: x in [x0, x1], y = y0
    tri((x0, y0, z0), (x0, y0, z1), (x1, y0, z1))
    tri((x0, y0, z0), (x1, y0, z1), (x1, y0, z0))
    # +X wall: x = x1, y in [y0, y1]
    tri((x1, y0, z0), (x1, y0, z1), (x1, y1, z1))
    tri((x1, y0, z0), (x1, y1, z1), (x1, y1, z0))
    # +Y wall: x in [x1, x0], y = y1
    tri((x1, y1, z0), (x1, y1, z1), (x0, y1, z1))
    tri((x1, y1, z0), (x0, y1, z1), (x0, y1, z0))
    # -X wall: x = x0, y in [y1, y0]
    tri((x0, y1, z0), (x0, y1, z1), (x0, y0, z1))
    tri((x0, y1, z0), (x0, y0, z1), (x0, y0, z0))

    # Inner side walls (4 faces) -- flipped winding so normals point inward.
    # -Y inner wall: y = iy0
    tri((ix0, iy0, z0), (ix1, iy0, z1), (ix0, iy0, z1))
    tri((ix0, iy0, z0), (ix1, iy0, z0), (ix1, iy0, z1))
    # +X inner wall: x = ix1
    tri((ix1, iy0, z0), (ix1, iy0, z1), (ix1, iy1, z1))
    tri((ix1, iy0, z0), (ix1, iy1, z1), (ix1, iy1, z0))
    # +Y inner wall: y = iy1
    tri((ix1, iy1, z0), (ix0, iy1, z1), (ix1, iy1, z1))
    tri((ix1, iy1, z0), (ix0, iy1, z0), (ix0, iy1, z1))
    # -X inner wall: x = ix0
    tri((ix0, iy1, z0), (ix0, iy1, z1), (ix0, iy0, z1))
    tri((ix0, iy1, z0), (ix0, iy0, z1), (ix0, iy0, z0))

    tri_arr = np.array(triangles, dtype=np.float32)         # (N, 3, 3)
    mesh_obj = _empty_stl_mesh(tri_arr.shape[0])
    mesh_obj.vectors[:] = tri_arr
    return mesh_obj


def make_depth_preview(
    source: Union[str, Path, Image.Image],
    width_mm: float,
    height_mm: float,
    lithotop_min_mm: float,
    lithotop_max_mm: float,
    border_width_mm: float = DEFAULT_BORDER_WIDTH_MM,
    px_per_mm: float = 4.0,
) -> Image.Image:
    """Render an instant 2.5D grayscale depth-map preview.

    The preview maps the image's BT.601 luminance onto a grayscale
    heightmap: white pixels (high luminance) become the thinnest
    columns; black pixels (low luminance) become the thickest columns.
    Border pixels are clamped to ``min`` so the border always prints
    thin.  The returned image is a PIL ``L`` mode image of size
    ``(width_mm * px_per_mm, height_mm * px_per_mm)``.

    This is a lightweight Pillow-only path designed for the live
    Streamlit preview; the heavy STL pipeline is run separately.
    """
    img = load_rgb_image(source)
    target_w = max(1, int(round(width_mm * px_per_mm)))
    target_h = max(1, int(round(height_mm * px_per_mm)))
    if img.size != (target_w, target_h):
        img = img.resize((target_w, target_h), resample=_RESAMPLE)

    # BT.601 luminance
    arr = np.asarray(img, dtype=np.float32) / 255.0      # H x W x 3
    luma = arr @ _LUMA_WEIGHTS                            # H x W

    # Pad with border (1.0 = thin = white in the preview)
    border_px = max(0, int(round(border_width_mm * px_per_mm)))
    if border_px > 0:
        luma = np.pad(
            luma,
            ((border_px, border_px), (border_px, border_px)),
            mode="constant", constant_values=1.0,
        )

    # Map [0,1] luminance -> [min,max] thickness, then invert for grayscale:
    # darker pixel = thicker column = darker in the preview.
    t_min = float(lithotop_min_mm)
    t_max = float(lithotop_max_mm)
    if t_max <= t_min:
        t_max = t_min + 0.1
    thickness = t_min + (1.0 - luma) * (t_max - t_min)
    thickness = np.clip(thickness, t_min, t_max)
    # Normalize to [0, 1] for display: max thickness -> 0 (black).
    gray = 1.0 - (thickness - t_min) / (t_max - t_min)
    gray_u8 = np.clip(gray * 255.0, 0, 255).astype(np.uint8)
    return Image.fromarray(gray_u8, mode="L")


# ---------------------------------------------------------------------------
# Result container + high-level entry point
# ---------------------------------------------------------------------------

@dataclass
class LithophaneResult:
    """Container for everything produced by :func:`process_image`."""

    rgb_normalized: np.ndarray           # (H, W, 3) float32 in [0, 1]
    cyan: np.ndarray                     # (H, W) float32 in [0, 1]
    magenta: np.ndarray                  # (H, W) float32 in [0, 1]
    yellow: np.ndarray                   # (H, W) float32 in [0, 1]
    luminance: np.ndarray                # (H, W) float32 in [0, 1]
    lithotop_z: np.ndarray               # (H, W) float32, top z in mm
    width_px: int
    height_px: int
    mesh_width_px: int
    mesh_height_px: int
    width_mm: float
    height_mm: float
    px_per_mm: float
    mesh_px_per_mm: float
    base_thickness_mm: float
    max_cmy_thickness_mm: float
    lithotop_min_mm: float
    lithotop_max_mm: float
    border_width_mm: float = 0.0
    effective_width_mm: float = 0.0
    effective_height_mm: float = 0.0
    # --- structural frame (optional) ---
    frame_enabled: bool = False
    frame_width_mm: float = DEFAULT_FRAME_WIDTH_MM
    frame_depth_mm: float = DEFAULT_FRAME_DEPTH_MM
    frame_bottom_z: float = 0.0
    frame_top_z: float = 0.0
    # --- STLs ---
    base_stl: Optional[object] = None    # numpy-stl Mesh or None
    cyan_layer_stl: Optional[object] = None
    magenta_layer_stl: Optional[object] = None
    yellow_layer_stl: Optional[object] = None
    lithotop_stl: Optional[object] = None
    frame_stl: Optional[object] = None    # hollow rectangular ring or None

    @property
    def channels(self) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Return ``(cyan, magenta, yellow)`` thickness arrays."""
        return self.cyan, self.magenta, self.yellow

    @property
    def shape(self) -> Tuple[int, int]:
        """Pixel resolution of the processed image ``(height, width)``."""
        return self.height_px, self.width_px

    @property
    def cmy_layers(self) -> Dict[str, object]:
        """Return ``{"cyan": ..., "magenta": ..., "yellow": ...}`` STLs."""
        return {
            "cyan": self.cyan_layer_stl,
            "magenta": self.magenta_layer_stl,
            "yellow": self.yellow_layer_stl,
        }

    def verify_alignment(self, atol: float = 1e-5, rtol: float = 1e-5):
        """Assert that all generated STL meshes share the same X/Y origin
        and bounding box.  See :func:`verify_xy_alignment` for details.

        Returns the bounds dict on success, raises ``ValueError`` on
        misalignment.
        """
        meshes = {
            "base": self.base_stl,
            "cyan": self.cyan_layer_stl,
            "magenta": self.magenta_layer_stl,
            "yellow": self.yellow_layer_stl,
            "lithotop": self.lithotop_stl,
        }
        return verify_xy_alignment(meshes, atol=atol, rtol=rtol)

    def summary(self) -> str:
        """Return a short human-readable summary of the result."""
        lines = [
            "Lithophane CMY result",
            f"  Physical size       : {self.width_mm} x {self.height_mm} mm",
            f"  CMY resolution      : {self.px_per_mm} px/mm "
            f"(~ {self.px_per_mm * 25.4:.1f} DPI)",
            f"  CMY pixel size      : {self.width_px} x {self.height_px} px",
            f"  Mesh resolution     : {self.mesh_px_per_mm} px/mm "
            f"(~ {self.mesh_px_per_mm * 25.4:.1f} DPI)",
            f"  Mesh pixel size     : {self.mesh_width_px} x "
            f"{self.mesh_height_px} px",
            f"  Base plate          : {self.base_thickness_mm:.2f} mm",
            f"  Max CMY thickness   : {self.max_cmy_thickness_mm:.2f} mm "
            f"per color layer",
            f"  Lithotop range      : {self.lithotop_min_mm:.2f} â€“ "
            f"{self.lithotop_max_mm:.2f} mm (above base+CMY)",
            f"  Channel stats (min, mean, max):",
        ]
        for name, arr in (("Cyan", self.cyan),
                          ("Magenta", self.magenta),
                          ("Yellow", self.yellow)):
            lines.append(
                f"    {name:7s}: "
                f"{arr.min():.4f}, {arr.mean():.4f}, {arr.max():.4f}"
            )
        lines.append(
            "  Luminance (min, mean, max): "
            f"{self.luminance.min():.4f}, {self.luminance.mean():.4f}, "
            f"{self.luminance.max():.4f}"
        )
        lines.append(
            "  Lithotop z   (min, mean, max): "
            f"{self.lithotop_z.min():.3f}, {self.lithotop_z.mean():.3f}, "
            f"{self.lithotop_z.max():.3f} mm"
        )
        stl_lines = []
        if self.base_stl is not None:
            stl_lines.append(
                f"    Base plate STL    : {self.base_stl.vectors.shape[0]} triangles"
            )
        for name in ("cyan", "magenta", "yellow"):
            mesh_obj = getattr(self, f"{name}_layer_stl")
            if mesh_obj is not None:
                stl_lines.append(
                    f"    {name.capitalize():7s} layer STL : "
                    f"{mesh_obj.vectors.shape[0]} triangles"
                )
        if self.lithotop_stl is not None:
            stl_lines.append(
                f"    Lithotop STL      : {self.lithotop_stl.vectors.shape[0]} triangles"
            )
        if stl_lines:
            lines.append("  STLs:")
            lines.extend(stl_lines)
        return "\n".join(lines)


def verify_xy_alignment(
    meshes: Dict[str, object],
    atol: float = 1e-5,
    rtol: float = 1e-5,
) -> Dict[str, Tuple[float, float, float, float]]:
    """Verify that every mesh in *meshes* shares the same X/Y bounding box.

    This is the alignment guarantee documented in the module docstring:
    when a slicer (Bambu Studio, PrusaSlicer, OrcaSlicer, ...) loads the
    five STLs produced by :func:`save_stls`, they will sit exactly on top
    of each other because every mesh uses the same X/Y origin and pixel
    grid.

    Parameters
    ----------
    meshes:
        Mapping of logical name -> numpy-stl ``Mesh``.  Any subset of
        ``{"base", "cyan", "magenta", "yellow", "lithotop"}`` is allowed.
    atol, rtol:
        Absolute and relative tolerances passed to ``numpy.isclose`` when
        comparing X/Y bounds.

    Returns
    -------
    A dict ``name -> (x_min, x_max, y_min, y_max)`` so the caller can see
    the exact bounds of each mesh.

    Raises
    ------
    ValueError
        If any pair of meshes disagrees on its X or Y bounds by more than
        the tolerance, or if any mesh has X/Y that don't start at zero
        (i.e. the meshes are not all anchored at the same origin).
    """
    if not meshes:
        raise ValueError("meshes dict is empty")
    bounds: Dict[str, Tuple[float, float, float, float]] = {}
    for name, m in meshes.items():
        if m is None:
            continue
        xs = m.vectors[:, :, 0]
        ys = m.vectors[:, :, 1]
        bounds[name] = (float(xs.min()), float(xs.max()),
                        float(ys.min()), float(ys.max()))

    if not bounds:
        raise ValueError("no non-None meshes to verify")

    ref_name, ref_box = next(iter(bounds.items()))
    for name, box in bounds.items():
        if name == ref_name:
            continue
        for axis_idx, (a, b) in enumerate(zip(ref_box, box)):
            if not np.isclose(a, b, atol=atol, rtol=rtol):
                axis_name = ("x_min", "x_max", "y_min", "y_max")[axis_idx]
                raise ValueError(
                    f"X/Y misalignment: mesh '{name}' {axis_name}={b} "
                    f"differs from reference mesh '{ref_name}' "
                    f"{axis_name}={a} (atol={atol}, rtol={rtol}).  "
                    "All STLs must share the same X/Y origin and extent."
                )
    return bounds


def _resize_for_mesh(
    img_rgb: Image.Image,
    width_mm: float,
    height_mm: float,
    mesh_px_per_mm: float,
    preserve_aspect: bool,
) -> Image.Image:
    """Resize *img_rgb* to the mesh grid size."""
    target_w_px, target_h_px = compute_target_pixels(
        img_rgb.size, width_mm, height_mm, mesh_px_per_mm, preserve_aspect
    )
    if img_rgb.size == (target_w_px, target_h_px):
        return img_rgb
    return img_rgb.resize((target_w_px, target_h_px), resample=_RESAMPLE)


def process_image(
    source: Union[str, Path, Image.Image],
    width_mm: float = 100.0,
    height_mm: float = 100.0,
    px_per_mm: float = 10.0,
    preserve_aspect: bool = True,
    # --- geometry parameters (base + per-channel CMY are hard-coded for
    #     standard CMYK filament profiles and are NOT exposed in the UI;
    #     the CLI still accepts them for power users) ---
    base_thickness_mm: float = DEFAULT_BASE_THICKNESS_MM,
    max_cmy_thickness_mm: float = DEFAULT_MAX_CMY_THICKNESS_MM,
    lithotop_min_mm: float = DEFAULT_LITHOTOP_MIN_MM,
    lithotop_max_mm: float = DEFAULT_LITHOTOP_MAX_MM,
    border_width_mm: float = DEFAULT_BORDER_WIDTH_MM,
    mesh_px_per_mm: Optional[float] = None,
    # --- structural outer frame ---
    frame_enabled: bool = DEFAULT_FRAME_ENABLED,
    frame_width_mm: float = DEFAULT_FRAME_WIDTH_MM,
    frame_depth_mm: float = DEFAULT_FRAME_DEPTH_MM,
    # --- output ---
    generate_stl: bool = True,
) -> LithophaneResult:
    """Run the full pipeline and return a :class:`LithophaneResult`.

    The returned result always contains the CMY thickness channels and the
    luminance field.  When ``generate_stl=True`` and ``numpy-stl`` is
    installed, the result also contains up to six STL meshes:

    * ``frame_stl``          -- (optional) hollow rectangular outer ring;
                                ``None`` when ``frame_enabled=False``
    * ``base_stl``           -- the flat base plate
    * ``cyan_layer_stl``     -- cyan color layer (flat bottom, heightmap top)
    * ``magenta_layer_stl``  -- magenta color layer
    * ``yellow_layer_stl``   -- yellow color layer
    * ``lithotop_stl``       -- top white (luminance) layer

    The CMY color layers are stacked on top of the base plate, each capped
    at ``max_cmy_thickness_mm`` (default **0.4 mm**).  The lithotop is
    stacked on top of the CMY stack.  The luminance value of every pixel
    is **automatically normalized** into the ``[lithotop_min_mm,
    lithotop_max_mm]`` range, so adjusting the two end-points rescales
    the whole 2.5D surface in a single click.

    ``base_thickness_mm`` and ``max_cmy_thickness_mm`` are hard-coded
    for standard CMYK filament profiles (0.6 mm and 0.4 mm) and are
    not surfaced in the Streamlit UI; the CLI accepts overrides for
    power users.
    """
    img = load_rgb_image(source)
    img_resized = resize_to_physical(
        img, width_mm, height_mm, px_per_mm, preserve_aspect
    )
    rgb_norm = np.asarray(img_resized, dtype=np.float32) / 255.0
    C, M, Y = rgb_to_cmy_thickness(rgb_norm)
    luma = rgb_to_luminance(rgb_norm)

    if mesh_px_per_mm is None:
        mesh_px_per_mm = px_per_mm
    if abs(mesh_px_per_mm - px_per_mm) < 1e-9:
        mesh_rgb_norm = rgb_norm
        mesh_width_px = img_resized.size[0]
        mesh_height_px = img_resized.size[1]
    else:
        mesh_img = _resize_for_mesh(
            img, width_mm, height_mm, mesh_px_per_mm, preserve_aspect
        )
        mesh_rgb_norm = np.asarray(mesh_img, dtype=np.float32) / 255.0
        mesh_width_px = mesh_img.size[0]
        mesh_height_px = mesh_img.size[1]

    # Re-derive CMY and luminance on the mesh grid.
    mesh_C, mesh_M, mesh_Y = rgb_to_cmy_thickness(mesh_rgb_norm)
    mesh_luma = rgb_to_luminance(mesh_rgb_norm)

    # ----- Border (Task 3) -----
    border_px = max(0, int(round(
        float(border_width_mm) * float(mesh_px_per_mm)
    )))
    effective_width_mm = float(width_mm) + 2.0 * float(border_width_mm)
    effective_height_mm = float(height_mm) + 2.0 * float(border_width_mm)
    mesh_C = _pad_with_ones(mesh_C, border_px)
    mesh_M = _pad_with_ones(mesh_M, border_px)
    mesh_Y = _pad_with_ones(mesh_Y, border_px)
    mesh_luma_padded = _pad_with_ones(mesh_luma, border_px)

    # Lithotop z map (top-Z in mm): sits on top of base + CMY stack.
    z_above_base = (
        float(base_thickness_mm) + 3.0 * float(max_cmy_thickness_mm)
    )
    lithotop_z = z_above_base + float(lithotop_min_mm) + (
        1.0 - mesh_luma_padded
    ) * float(lithotop_max_mm - lithotop_min_mm)

    base_stl = None
    cyan_layer_stl = None
    magenta_layer_stl = None
    yellow_layer_stl = None
    lithotop_stl = None
    frame_stl = None

    # Frame Z placement: the frame sits *under* the base plate so the
    # border thickness belongs to the frame, not the base.  This way the
    # border's depth is independent of the base plate thickness.
    frame_bottom_z = 0.0
    frame_top_z = float(frame_depth_mm) if frame_enabled else 0.0

    if generate_stl and _HAS_NUMPY_STL:
        # Structural outer frame first (sits under the base plate).
        if frame_enabled and frame_width_mm > 0 and frame_depth_mm > 0:
            frame_stl = make_frame_stl(
                width_mm=effective_width_mm,
                height_mm=effective_height_mm,
                frame_width_mm=float(frame_width_mm),
                frame_depth_mm=float(frame_depth_mm),
                bottom_z=frame_bottom_z,
            )
        base_stl = make_base_plate_stl(
            effective_width_mm,
            effective_height_mm,
            base_thickness_mm,
        )
        # Lift the base on top of the frame when the frame is enabled.
        base_bottom_z = float(frame_top_z) if frame_enabled else 0.0
        if frame_enabled and base_bottom_z > 0.0:
            base_stl.vectors[:, :, 2] += base_bottom_z
        # The CMY stack sits on top of the (possibly lifted) base.
        cmy_stack_bottom_z = base_bottom_z + float(base_thickness_mm)
        cmy_layers = make_cmy_layers_stls(
            width_mm=effective_width_mm,
            height_mm=effective_height_mm,
            cyan=mesh_C,
            magenta=mesh_M,
            yellow=mesh_Y,
            max_thickness_mm=max_cmy_thickness_mm,
            base_bottom_z=cmy_stack_bottom_z,
        )
        cyan_layer_stl = cmy_layers["cyan"]
        magenta_layer_stl = cmy_layers["magenta"]
        yellow_layer_stl = cmy_layers["yellow"]
        # The lithotop sits on top of the (possibly lifted) CMY stack.
        lithotop_z_stl = cmy_stack_bottom_z + 3.0 * float(max_cmy_thickness_mm)
        lithotop_stl = make_lithotop_stl(
            width_mm=effective_width_mm,
            height_mm=effective_height_mm,
            base_thickness_mm=base_thickness_mm,
            rgb_normalized=_pad_with_ones(mesh_rgb_norm, border_px),
            lithotop_min_mm=lithotop_min_mm,
            lithotop_max_mm=lithotop_max_mm,
            lithotop_bottom_z=lithotop_z_stl,
        )
        # The Numpy lithotop_z map needs the same baseline so that
        # the preview matches the STL geometry.
        z_above_base = lithotop_z_stl
        lithotop_z = lithotop_z_stl + float(lithotop_min_mm) + (
            1.0 - mesh_luma_padded
        ) * float(lithotop_max_mm - lithotop_min_mm)

    return LithophaneResult(
        rgb_normalized=rgb_norm,
        cyan=C,
        magenta=M,
        yellow=Y,
        luminance=luma,
        lithotop_z=lithotop_z.astype(np.float32),
        width_px=img_resized.size[0],
        height_px=img_resized.size[1],
        mesh_width_px=mesh_C.shape[1],
        mesh_height_px=mesh_C.shape[0],
        width_mm=width_mm,
        height_mm=height_mm,
        px_per_mm=px_per_mm,
        mesh_px_per_mm=mesh_px_per_mm,
        base_thickness_mm=base_thickness_mm,
        max_cmy_thickness_mm=max_cmy_thickness_mm,
        lithotop_min_mm=lithotop_min_mm,
        lithotop_max_mm=lithotop_max_mm,
        border_width_mm=float(border_width_mm),
        effective_width_mm=effective_width_mm,
        effective_height_mm=effective_height_mm,
        frame_enabled=bool(frame_enabled),
        frame_width_mm=float(frame_width_mm),
        frame_depth_mm=float(frame_depth_mm),
        frame_bottom_z=float(frame_bottom_z),
        frame_top_z=float(frame_top_z),
        base_stl=base_stl,
        cyan_layer_stl=cyan_layer_stl,
        magenta_layer_stl=magenta_layer_stl,
        yellow_layer_stl=yellow_layer_stl,
        lithotop_stl=lithotop_stl,
        frame_stl=frame_stl,
    )


# ---------------------------------------------------------------------------
# Output / preview helpers
# ---------------------------------------------------------------------------

def _to_uint8(arr: np.ndarray) -> np.ndarray:
    """Convert a float array in [0, 1] to uint8, clipping safely."""
    return np.clip(arr * 255.0, 0, 255).astype(np.uint8)


def save_preview(
    result: LithophaneResult,
    output_dir: Union[str, Path],
    base_name: Optional[str] = None,
    also_save_npy: bool = True,
) -> Dict[str, Path]:
    """Save per-channel preview PNGs and (optionally) raw ``.npy`` files."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    base_name = base_name or "lithophane"

    paths: Dict[str, Path] = {}

    for label, arr in (("cyan", result.cyan),
                       ("magenta", result.magenta),
                       ("yellow", result.yellow)):
        png_path = output_dir / f"{base_name}_{label}.png"
        Image.fromarray(_to_uint8(arr), mode="L").save(png_path)
        paths[label] = png_path

    rgb_path = output_dir / f"{base_name}_rgb.png"
    Image.fromarray(_to_uint8(result.rgb_normalized), mode="RGB").save(rgb_path)
    paths["rgb"] = rgb_path

    composite = np.stack(
        [_to_uint8(result.cyan),
         _to_uint8(result.magenta),
         _to_uint8(result.yellow)],
        axis=-1,
    )
    composite_path = output_dir / f"{base_name}_composite.png"
    Image.fromarray(composite, mode="RGB").save(composite_path)
    paths["composite"] = composite_path

    if also_save_npy:
        for label, arr in (("cyan", result.cyan),
                           ("magenta", result.magenta),
                           ("yellow", result.yellow)):
            np.save(output_dir / f"{base_name}_{label}.npy",
                    arr.astype(np.float32))
        np.save(output_dir / f"{base_name}_rgb.npy",
                result.rgb_normalized.astype(np.float32))
        np.save(output_dir / f"{base_name}_luminance.npy",
                result.luminance.astype(np.float32))
        np.save(output_dir / f"{base_name}_lithotop_z.npy",
                result.lithotop_z.astype(np.float32))

    return paths


#: Slicer-friendly STL file names, in load order.  The optional ``"frame"``
#: mesh is numbered ``0`` so most slicers load it FIRST and use it as
#: the structural bottom of the print.
STL_FILE_NAMES: Dict[str, str] = {
    "frame":    "0_Frame.stl",
    "base":     "1_Base_White.stl",
    "cyan":     "2_Cyan.stl",
    "magenta":  "3_Magenta.stl",
    "yellow":   "4_Yellow.stl",
    "lithotop": "5_Top_White.stl",
}


def save_stls(
    result: LithophaneResult,
    output_dir: Union[str, Path],
    base_name: Optional[str] = None,
    include_frame: Optional[bool] = None,
) -> Dict[str, Path]:
    """Save the base, CMY color layer and lithotop STLs.

    The five files are written with numbered, slicer-friendly names
    (see :data:`STL_FILE_NAMES`):

    =================  ===========================
    Key                Default filename
    =================  ===========================
    ``"base"``         ``1_Base_White.stl``
    ``"cyan"``         ``2_Cyan.stl``
    ``"magenta"``      ``3_Magenta.stl``
    ``"yellow"``       ``4_Yellow.stl``
    ``"lithotop"``     ``5_Top_White.stl``
    =================  ===========================

    The numeric prefixes force the load order in most slicers; the
    colour names make the files self-documenting.

    All five meshes are guaranteed to share the same X/Y origin and
    bounding box (see :func:`verify_xy_alignment` and the module
    docstring's "Alignment guarantee" section).

    Parameters
    ----------
    result:
        The :class:`LithophaneResult` returned by :func:`process_image`.
    output_dir:
        Directory where the STLs are written (created if missing).
    base_name:
        Optional prefix prepended to every filename.  When ``None`` (the
        default) the files are written exactly as
        :data:`STL_FILE_NAMES` lists them -- ready for Bambu Studio /
        PrusaSlicer / OrcaSlicer to load in order.

    Returns
    -------
    Dict mapping ``"base" | "cyan" | "magenta" | "yellow" | "lithotop"``
    to the file path written for each mesh.
    """
    meshes: Dict[str, object] = {
        "base": result.base_stl,
        "cyan": result.cyan_layer_stl,
        "magenta": result.magenta_layer_stl,
        "yellow": result.yellow_layer_stl,
        "lithotop": result.lithotop_stl,
    }
    # Frame is OPTIONAL: only include it if it was actually generated.
    if include_frame is None:
        include_frame = getattr(result, "frame_stl", None) is not None
    if include_frame and getattr(result, "frame_stl", None) is not None:
        meshes["frame"] = result.frame_stl

    # Only complain about missing meshes for the ones we are actually writing.
    missing = [k for k, v in meshes.items() if v is None]
    if missing:
        raise RuntimeError(
            f"No STL data for {missing}.  Make sure generate_stl=True and "
            "numpy-stl is installed."
        )

    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    paths: Dict[str, Path] = {}
    # Write files in the canonical numeric order so slicers always see
    # them in 0 -> 5 order regardless of dict insertion order.
    ordered_keys = sorted(
        meshes.keys(),
        key=lambda k: STL_FILE_NAMES[k],
    )
    for name in ordered_keys:
        mesh_obj = meshes[name]
        filename = STL_FILE_NAMES[name]
        if base_name:
            filename = f"{base_name}_{filename}"
        path = output_dir / filename
        save_binary_stl(mesh_obj, path)
        paths[name] = path
    return paths


def _numpy_stl_to_trimesh(stl_mesh):
    """Convert a numpy-stl Mesh to a trimesh.Trimesh."""
    vertices = stl_mesh.vectors.reshape(-1, 3)
    unique, inverse = np.unique(vertices, axis=0, return_inverse=True)
    faces = inverse.reshape(-1, 3).astype(np.int64)
    return _trimesh.Trimesh(vertices=unique, faces=faces, process=False)


def _trimesh_to_numpy_stl(tri, dtype):
    """Convert a trimesh.Trimesh back into a numpy-stl Mesh array."""
    n = len(tri.faces)
    out = np.zeros(n, dtype=dtype)
    out["vectors"][:, 0] = tri.vertices[tri.faces[:, 0]]
    out["vectors"][:, 1] = tri.vertices[tri.faces[:, 1]]
    out["vectors"][:, 2] = tri.vertices[tri.faces[:, 2]]
    return out


def simplify_meshes(
    meshes,
    target_face_count=None,
    merge_tolerance=1e-5,
):
    """Simplify every numpy-stl Mesh in *meshes* using trimesh.

    Stage 1: merge_vertices (removes duplicates shared between
             adjacent pixel columns -- huge triangle-count win).
    Stage 2 (optional): quadric-error-mesh decimation to
             *target_face_count* triangles.

    Returns a new dict ``name -> numpy-stl.Mesh`` and stashes before /
    after counts in ``simplify_meshes._stats``.
    """
    _require_stl()
    if not _HAS_TRIMESH:
        raise RuntimeError(
            "trimesh is required for mesh simplification but is not "
            "installed.  Install it with:  pip install trimesh"
        )
    out = {}
    for name, stl_mesh in meshes.items():
        if stl_mesh is None:
            out[name] = None
            continue
        tri = _numpy_stl_to_trimesh(stl_mesh)
        # Stage 1: merge coincident vertices.  trimesh 4.x has multiple
        # ways to do this; we use merge_vertices() with no args (which
        # merges by default tolerance) plus process() to deduplicate
        # and clean up.  We wrap process() in a try/except because some
        # trimesh builds require scipy._propack (DLL not always present).
        try:
            tri.merge_vertices()
        except TypeError:
            # Older trimesh accepts a `digits` kwarg
            tri.merge_vertices(digits=int(-np.log10(merge_tolerance)))
        try:
            tri.process(validate=False)
        except Exception:
            # process() can fail on missing scipy/numpy-stl-bundled
            # native libs; the mesh is still valid for simplification.
            pass
        before = len(tri.faces)
        if (
            target_face_count is not None
            and target_face_count > 0
            and target_face_count < before
        ):
            try:
                tri = tri.simplify_quadric_decimation(
                    face_count=int(target_face_count)
                )
            except Exception as e:
                print(
                    f"simplify_meshes: QEM failed for {name!r} ({e}); "
                    "skipping decimation for this mesh.",
                    flush=True,
                )
        after = len(tri.faces)
        arr = _trimesh_to_numpy_stl(tri, _stl_mesh.Mesh.dtype)
        out[name] = _stl_mesh.Mesh(arr)
        if not hasattr(simplify_meshes, "_stats"):
            simplify_meshes._stats = {}
        simplify_meshes._stats[name] = (before, after)
    return out


def save_binary_stl(stl_mesh, path):
    """Save a numpy-stl Mesh as a **binary** STL (about half the size
    of ASCII).  Falls back to ASCII on older numpy-stl.
    """
    from pathlib import Path as _P
    p = _P(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    try:
        from stl import Mode as _Mode
        stl_mesh.save(str(p), mode=_Mode.BINARY)
    except (ImportError, TypeError):
        # Older numpy-stl without Mode enum or without mode kwarg
        try:
            stl_mesh.save(str(p), mode=2)  # 2 = BINARY in older versions
        except TypeError:
            stl_mesh.save(str(p))
    return p


def make_demo_image(size: Tuple[int, int] = (640, 480)) -> Image.Image:
    """Return a synthetic RGB image useful for testing."""
    w, h = size
    img = Image.new("RGB", (w, h), (0, 0, 0))
    px = img.load()
    for y in range(h):
        for x in range(w):
            r = int(255 * (y / max(1, h - 1)))
            g = int(255 * (x / max(1, w - 1)))
            b = int(255 * ((x + y) / max(1, w + h - 2)))
            px[x, y] = (r, g, b)
    for y in range(h // 6, h // 3):
        for x in range(w // 6, w // 3):
            px[x, y] = (255, 255, 255)
    return img


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _build_arg_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description=(
            "Convert an RGB image into CMY thickness channels for a "
            "3D-printed CMY lithophane and emit base-plate, CMY color-layer "
            "and lithotop STL meshes."
        ),
    )
    p.add_argument("image", nargs="?",
                   help="Path to the input image.  Omit with --demo.")
    p.add_argument("--width", type=float, default=100.0)
    p.add_argument("--height", type=float, default=100.0)
    p.add_argument("--px-per-mm", type=float, default=10.0,
                   help="CMY channel XY resolution in px/mm (default: 10).")
    p.add_argument("--no-aspect", action="store_true")
    p.add_argument("--out-dir", default="output")
    p.add_argument("--base-name", default=None)
    p.add_argument("--no-npy", action="store_true")
    # --- STL / geometry ---------------------------------------------------
    p.add_argument("--no-stl", action="store_true",
                   help="Skip ALL STL generation (CMY channels only).")
    p.add_argument("--base-thickness-mm", type=float,
                   default=DEFAULT_BASE_THICKNESS_MM,
                   help=f"Base plate thickness in mm "
                        f"(default: {DEFAULT_BASE_THICKNESS_MM}).")
    p.add_argument("--max-cmy-thickness-mm", type=float,
                   default=DEFAULT_MAX_CMY_THICKNESS_MM,
                   help=f"Max thickness PER CMY color layer in mm "
                        f"(default: {DEFAULT_MAX_CMY_THICKNESS_MM}).")
    p.add_argument("--lithotop-min-mm", type=float,
                   default=DEFAULT_LITHOTOP_MIN_MM)
    p.add_argument("--lithotop-max-mm", type=float,
                   default=DEFAULT_LITHOTOP_MAX_MM)
    p.add_argument("--mesh-px-per-mm", type=float, default=None,
                   help="STL mesh resolution in px/mm (default: same as "
                        "--px-per-mm).  Set lower to keep STL files small.")
    p.add_argument("--border-width-mm", type=float,
                   default=DEFAULT_BORDER_WIDTH_MM,
                   help=f"Solid frame around the perimeter, mm "
                        f"(default: {DEFAULT_BORDER_WIDTH_MM}, 0 = off).")
    p.add_argument("--frame-width-mm", type=float,
                   default=DEFAULT_FRAME_WIDTH_MM,
                   help=f"Structural outer ring X/Y thickness in mm "
                        f"(default: {DEFAULT_FRAME_WIDTH_MM}, 0 = off).")
    p.add_argument("--frame-depth-mm", type=float,
                   default=DEFAULT_FRAME_DEPTH_MM,
                   help=f"Structural outer ring Z thickness in mm "
                        f"(default: {DEFAULT_FRAME_DEPTH_MM}, 0 = off).")
    p.add_argument("--no-frame", action="store_true",
                   help="Disable the structural frame ring (0_Frame.stl).")
    p.add_argument("--simplify-faces", type=int, default=None,
                   help="Optional: target face count after trimesh QEM "
                        "decimation (e.g. 50000).  Default: no decimation.")
    p.add_argument("--no-simplify", action="store_true",
                   help="Skip the trimesh merge_vertices pass too.")
    p.add_argument("--demo", action="store_true")
    return p


def main(argv: Optional[list] = None) -> int:
    args = _build_arg_parser().parse_args(argv)

    if args.demo:
        source = make_demo_image()
        base_name = args.base_name or "lithophane"
        source_desc = "synthetic demo image"
    else:
        if not args.image:
            print("error: please provide an image path or pass --demo",
                  flush=True)
            return 2
        source = args.image
        base_name = args.base_name or Path(args.image).stem
        source_desc = str(args.image)

    result = process_image(
        source,
        width_mm=args.width,
        height_mm=args.height,
        px_per_mm=args.px_per_mm,
        preserve_aspect=not args.no_aspect,
        base_thickness_mm=args.base_thickness_mm,
        max_cmy_thickness_mm=args.max_cmy_thickness_mm,
        lithotop_min_mm=args.lithotop_min_mm,
        lithotop_max_mm=args.lithotop_max_mm,
        border_width_mm=args.border_width_mm,
        frame_enabled=not args.no_frame,
        frame_width_mm=args.frame_width_mm,
        frame_depth_mm=args.frame_depth_mm,
        mesh_px_per_mm=args.mesh_px_per_mm,
        generate_stl=not args.no_stl,
    )

    print(f"Source           : {source_desc}", flush=True)
    print(result.summary(), flush=True)

    paths = save_preview(
        result,
        output_dir=args.out_dir,
        base_name=base_name,
        also_save_npy=not args.no_npy,
    )
    print("\nWrote previews:", flush=True)
    for name, path in paths.items():
        print(f"  {name:9s} -> {path}", flush=True)

    if not args.no_stl:
        if result.base_stl is None:
            print(
                "\nwarning: numpy-stl is not installed - skipping STL "
                "output (run `pip install numpy-stl` to enable).",
                flush=True,
            )
        else:
            # Alignment sanity check (prints explicit X/Y bounds per
            # mesh, raises if any pair disagrees).
            bounds = result.verify_alignment()
            print("\nX/Y alignment check (all meshes must agree):", flush=True)
            for name, (x0, x1, y0, y1) in bounds.items():
                print(f"  {name:8s}  x=[{x0:.3f}, {x1:.3f}]  "
                      f"y=[{y0:.3f}, {y1:.3f}]", flush=True)

            # Optional mesh simplification via trimesh (Task 2).
            # Skip when --no-simplify is set or trimesh is unavailable.
            if not args.no_simplify and _HAS_TRIMESH:
                pre = {
                    "base":     result.base_stl,
                    "cyan":     result.cyan_layer_stl,
                    "magenta":  result.magenta_layer_stl,
                    "yellow":   result.yellow_layer_stl,
                    "lithotop": result.lithotop_stl,
                }
                if result.frame_stl is not None:
                    pre["frame"] = result.frame_stl
                print("\nSimplifying meshes with trimesh ...", flush=True)
                simplified = simplify_meshes(
                    pre, target_face_count=args.simplify_faces
                )
                result.base_stl = simplified["base"]
                result.cyan_layer_stl = simplified["cyan"]
                result.magenta_layer_stl = simplified["magenta"]
                result.yellow_layer_stl = simplified["yellow"]
                result.lithotop_stl = simplified["lithotop"]
                if "frame" in simplified:
                    result.frame_stl = simplified["frame"]
                if hasattr(simplify_meshes, "_stats"):
                    for name, (b, a) in simplify_meshes._stats.items():
                        pct = 100.0 * a / max(b, 1)
                        print(f"    {name:8s}: {b:>9,} -> {a:>9,} "
                              f"triangles  ({pct:5.1f}%)", flush=True)
            stl_paths = save_stls(
                result, output_dir=args.out_dir, base_name=args.base_name
            )
            print("\nWrote STLs:", flush=True)
            for name, path in stl_paths.items():
                size_kb = path.stat().st_size / 1024
                print(f"  {name:8s} -> {path}  ({size_kb:.1f} KB)",
                      flush=True)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
